### ISSUE TITLE
Скобки у инструкции объявления переменной/константы

### ISSUE THREAD

**Issue by i582** [Ramzeeset/Compiler-Cpm#1]
Привет. Я проверяю твое тестовое задание в команду KPHP. Проверяя его, я сразу же наткнулся на такую ошибку.

Я компилирую следующий код:
```kotlin
// test.cpm
val answerNumber = 42;
val numberString = "134";
print(numberString - answerNumber);
print(numberString + answerNumber);
```

Следующей командой:
```
cpm test.cpm -cmp=/usr/bin/clang++
```

В итоге C++ код выглядит следующим образом:
```cpp
// ...

int main() {
  (val answerNumber = 42);
  (val numberString = std::string("134"));
  print((numberString - answerNumber));
  print((numberString + answerNumber));

  return 0;
}
```

Здесь меня и компилятор смущают скобки в `(val answerNumber = 42);`, подскажи, возможно я что-то делаю не так, потому что в текущем виде оно не компилируется?

**Comment by astrophysik** [comment]
Здравствуйте, я совершил фатальную ошибку, изменив строчку и не проверив работоспособность. Ошибка в файле translator.cpp в 12 строчке. Там результат операции берется в скобки

**Comment by i582** [comment]
> Здравствуйте, я совершил фатальную ошибку, изменив строчку и не проверив работоспособность. Ошибка в файле translator.cpp в 12 строчке. Там результат операции берется в скобки

Ничего страшного, я исправлю там ошибку и будем считать что ее не было 😄
